version: '3'

services:
  database:
    container_name: buddy-database
    image: mariadb
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
  cache:
    container_name: buddy-cache
    image: redis
    ports:
      - ${CACHE_PORT}:6379
